title: Syazwina's Blog
author: syzwina
email: nor.syazwina.ahmad.fazrul@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I am testing this hosting feature.

# social links
twitter_username: norsyzwina # DO NOT include the @ character, or else the build will fail!
github_username:  syzwina # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
